#!/bin/bash

yum update -y 
# START

cat > /tmp/subscript.sh << EOF
echo "Setting up NodeJS Environment"
curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
echo 'export NVM_DIR="/home/ec2-user/.nvm"' >> ~/.bashrc
echo '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm' >> ~/.bashrc

# Dot source the files to ensure that variables are available within the current shell
. ~/.nvm/nvm.sh
. ~/.bashrc

# Install NVM, NPM, Node.JS & Grunt
nvm alias default v16
nvm install v16
nvm use v16

nvm ls
EOF

chown ec2-user:ec2-user /tmp/subscript.sh && chmod a+x /tmp/subscript.sh
su - ec2-user -c "/tmp/subscript.sh"

# Install repo data
su - ec2-user -c "npm install -g pm2@latest"

yum install git -y
su - ec2-user -c "{{github-repo}}"
cd /home/ec2-user/{{repo-name/foldername}}
npm install
su - ec2-user -c "pm2 start /home/ec2-user/ec2-asg/index.js"
su - ec2-user -c "pm2 startup"
su - ec2-user -c "pm2 save"
